### ISSUE TITLE
question

### ISSUE THREAD

**Issue by joeblew99** [YuriyNasretdinov/GoSSHa#5]
so does this require any other software o the client or server. Its 100% golang ?

**Comment by YuriyNasretdinov** [comment]
It requires an openssh-compatible server at the other end. There exist pure-go ssh servers as well, but GoSSHa is just a client.

**Comment by joeblew99** [comment]
Ah. I am looking for pure go open SSH. Do you happen to know any ? Been hard to find.

**Comment by YuriyNasretdinov** [comment]
I do not think that it is a good idea, to be honest. OpenSSH is very good
and robust, it is highly unlikely that pure-go server will perform better.
If you need openssh under windows, you can set up cygwin openssh-server,
although it is pretty hard to install

**Comment by joeblew99** [comment]
I see your point.
My use case is that I need SSH between data Center server, remote workstation ( mix of windows, Linux) and arm stuff like raspberry pi, raspberry zero.

The traffic will be very low, so perf is not important all.

The SSH code will be compiled in with some other golang code so its a single binary, SSH will be  just sitting at runtime inside a spinning go routine.

So it all about getting it all as a golang thing to reduce out the dependencies, hassles across the many os's.

Curious what your assessment is based on my use case ?
